### ISSUE TITLE
Just use the markup to add the classname <img class="meal-tile" src="/public/...

### ISSUE THREAD

**Issue by benna100** [cecastosic/meal-sharing#2]
https://github.com/cecastosic/meal-sharing/blob/597874b3f0e8efa825da94338e0fdfd34e406c9c/src/frontend/pages/common/fetchMealWithId.js#L16

**Comment by cecastosic** [comment]
But I want to add class to the div that I made in the previous two lines:
    const divTile = document.createElement("div");
    mealsSection.append(divTile);
    divTile.className = "meal-tile";

**Comment by benna100** [comment]
Ahh sorry you are correct, i misread that!
